package org.mailster.smtp.core.commands;

import java.io.IOException;


/**
 * Exception generated by the commands.
 * 
 * @author Ian McFarland &lt;ian@neo.com&gt;
 * @author De Oliveira Edouard &lt;doe_wanted@yahoo.fr&gt;
 */
public class CommandException 
	extends IOException
{
	private static final long serialVersionUID = -1429848828296942017L;

	/**
	 * {@inheritDoc}
	 */
	public CommandException(String string, Throwable throwable)
	{
		super(string, throwable);
	}

	/**
	 * {@inheritDoc}
	 */
	public CommandException(String string)
	{
		super(string);
	}

	/**
	 * {@inheritDoc}
	 */
	public CommandException()
	{
		super();
	}

	/**
	 * {@inheritDoc}
	 */
	public CommandException(Throwable throwable)
	{
		super(throwable);
	}
}
